# Generated by Django 4.2.2 on 2023-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.TextField(max_length=50)),
                ('yourmessage', models.CharField(max_length=2000)),
            ],
        ),
    ]
