# Generated by Django 4.2.2 on 2023-09-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(upload_to='cv_files/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
